#!/bin/bash
## Author: Hakxcore https://github.com/hakxcore
## Colors
currentVersion="2.1.2"

##Platform Check
distr_name=$1
if [ "$distr_name" == "Android" ]; then
  platform="Termux"
  prefix="/data/data/com.termux/files/"
  else
    platform="Debian"
    prefix=""
fi

checkDialog()
{
  if  command -v dialog &>/dev/null; then
    echo ""
  else
    echo $BLUE"Error: Dialog should be installed"$RESETBG
    echo $BLUE"use $RED'apt install dialog'$BLUE firstly"$RESETBG
    exit 1
  fi 
}

# while-menu-dialog: a menu driven Operating system chooseing Installation  program

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

display_termux() {
  dialog --prgbox $1 ./installation 50 80
}

display_debian() {
  dialog --prgbox $1 ./installation 50 80
}

checkDialog
while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "Hakxcore Here" \
    --title "termux-snippets" \
    --clear \
    --cancel-label "Exit" \
    --menu "Choose OS:" $HEIGHT $WIDTH 4 \
    "1" "Termux" \
    "2" "Debian OS" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    1 )
      display_termux "TERMUX"
      ;;
    2 )
      result=$(echo "Debian";)
      display_debian "DEBIAN"
      ;;
  esac
done

