#!/usr/bin/env bash
## Author: Hakxcore https://github.com/hakxcore
## colors
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')" 
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')"  BLACK="$(printf '\033[30m')"  
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"  
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')"  BLACKBG="$(printf '\033[40m')" 
RESETBG="$(printf '\e[0m')"  BLINK="$(printf '\033[5;31m')"

declare -a tools=(termux-snippets cheat cipher covidinfo crypt cryptocurrency geo gif googler ipinfo jukebox lyrics meme movie news pwned qrify shodan shorturl todo transfer weather)
all="1"

##Platform Check
distr_name=$1
if [ "$distr_name" == "Android" ]; then
  platform="Termux"
  prefix="/data/data/com.termux/files/"
  else
    platform="Debian"
    prefix=""
fi

askUninstall()
{
  if [[ -f $prefix/usr/bin/$1 ]]; then
    echo -n "$BLUE>$RESETBG Do you wish to uninstall $BLUE$1$RESETBG [Y/n]: "
    read -r answer
    if [[ "$answer" == [Yy] ]]; then
      echo -n "Removing $1: "
      rm -f $prefix/usr/bin/$1 > /dev/null 2>&1 || { echo "Failed" ; echo "Error removing file, try running uninstall script again"; exit 1; }
      echo ""$GREEN"Success$RESETBG"
    else
      all="0"
    fi
    unset answer
  fi
}

removeTool()
{
  if [[ -f $prefix/usr/bin/$1 ]]; then
    echo -n "Removing $1: "
    rm -f $prefix/usr/bin/$1 > /dev/null 2>&1 || { echo "Failed" ; echo "Error removing file, try running uninstall script again"; exit 1; }
    echo ""$GREEN"Success$RESETBG"
  fi
}

##Driver
if [[ $1 != "all" ]]; then
  for tool in "${tools[@]}"; do
    askUninstall $tool || exit 1
  done
else
  for tool in "${tools[@]}"; do
    removeTool $tool || exit 1
  done
fi
