#!/usr/bin/env bash
# Author: Hakxcore https://github.com/hakxcore
currentVersion="2.1.2"
configuredClient=""

#colors
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')" 
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')"  BLACK="$(printf '\033[30m')"  
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"  
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')"  BLACKBG="$(printf '\033[40m')" 
RESETBG="$(printf '\e[0m')"  BLINK="$(printf '\033[5;31m')"

## This function determines which http get tool the system has installed and returns an error if there isnt one
getConfiguredClient()
{
  if  command -v curl &>/dev/null; then
    configuredClient="curl"
  elif command -v wget &>/dev/null; then
    configuredClient="wget"
  elif command -v http &>/dev/null; then
    configuredClient="httpie"
  elif command -v fetch &>/dev/null; then
    configuredClient="fetch"
  else
    echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
    return 1
  fi
}

##This function determines is python installed or not 
getConfiguredPython()
{
  if command -v python3 &>/dev/null; then
    configuredPython="python3"
  elif  command -v python2 &>/dev/null; then
    configuredPython="python2"
  elif command -v python &>/dev/null; then
    configuredPython="python"
  else
    echo "Error: This tool requires python to be installed."
    return 1
  fi
}

##Determines the version of python
if [[ $(uname) != "Hakxcore" ]]; then
  python()
  {
    case "$configuredPython" in
      python3) python3 "$@" ;;
      python2) python2 "$@" ;;
      python)  python "$@" ;;
    esac
  }
fi

## Allows to call the users configured client without if statements everywhere
httpGet()
{
  case "$configuredClient" in
    curl)  curl -A curl -s "$@" ;;
    wget)  wget -qO- "$@" ;;
    httpie) http -b GET "$@" ;;
    fetch) fetch -q "$@" ;;
  esac
}

##determines weather pv package is installed or not
getConfiguredpv()
{
	if command -v pv &>/dev/null; then
		configuredpv="pv"
	else
		echo "pv needs to be installed"
		echo "use 'apt install pv' then start again all the best"
	fi
}

##This function determines the latest version of the termux-snippets if available and installs them
update()
{
  repositoryName="termux-snippets" 
  githubUserName="hakxcore" 
  nameOfInstallFile="install" 
  latestVersion=$(curl -s https://api.github.com/repos/$githubUserName/$repositoryName/tags | grep -Eo '"name":.*?[^\\]",'| head -1 | grep -Eo "[0-9.]+" ) #always grabs the tag without the v option

  if [[ $currentVersion == "" || $repositoryName == "" || $githubUserName == "" || $nameOfInstallFile == "" ]]; then
    echo "Error: update utility has not been configured correctly." >&2
    exit 1
  elif [[ $latestVersion == "" ]]; then
    echo "Error: no active internet connection" >&2
    exit 1
  else
    if [[ "$latestVersion" != "$currentVersion" ]]; then
      echo "Version $latestVersion available"
      echo -n "Do you wish to update $repositoryName [Y/n]: "
      read -r answer
      if [[ "$answer" == [Yy] ]]; then
        cd ~ || { echo 'Update Failed'; exit 1; }
        if [[ -d  ~/$repositoryName ]]; then rm -r -f $repositoryName || { echo "Permissions Error: try running the update again"; exit 1; } ; fi
        git clone "https://github.com/$githubUserName/$repositoryName" || { echo "Couldn't download latest version"; exit 1; }
        cd $repositoryName || { echo 'Update Failed'; exit 1; }
        git checkout "v$latestVersion" 2> /dev/null || git checkout "$latestVersion" 2> /dev/null || echo "Couldn't git checkout to stable release, updating to latest commit."
        ./$nameOfInstallFile "update" || exit 1
        cd ..
        rm -r -f $repositoryName || { echo "Permissions Error: update succesfull but cannot delete temp files located at ~/$repositoryName delete this directory again"; exit 1; }
      else
        exit 1
      fi
    else
      echo "$repositoryName is already the latest version"
    fi
  fi
}

##This function Checks for the insternet connectivity
checkInternet()
{
  httpGet github.com > /dev/null 2>&1 || { echo "Error: no active internet connection" >&2; return 1; } # query github with a get request
}

##Main function
main()
{
	clear
	echo ""$BLUE"Please wait.......$RESETBG" | pv -qL 10
	echo ""$WHITEBG"=================================================================================================================================================================$RESETBG"
	echo "                                                  "$BLINK$BLACKBG$GREEN"COVID-19 COUNTRY WISE INFORMATION$RESETBG                                                        "
	echo ""$WHITEBG"-----------------------------------------------------------------------------------------------------------------------------------------------------------------$RESETBG"
	sleep 3.0
	curl https://corona-stats.online
	echo ""$WHITEBG"_________________________________________________________________________________________________________________________________________________________________$RESETBG"
	echo ""$WHITEBG"=================================================================================================================================================================$RESETBG"
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""$WHITEBG"========================================================================================================================================$RESETBG"
	echo "                                                     "$BLINK$BLACKBG$GREEN"COVID-19 WORLD INFORMATION$RESETBG                                                            "
	echo ""$WHITEBG"----------------------------------------------------------------------------------------------------------------------------------------$RESETBG"
	sleep 3.0
	curl -L covid19.trackercli.com
	echo ""$WHITEBG"________________________________________________________________________________________________________________________________________$RESETBG"
	echo ""$WHITEBG"========================================================================================================================================$RESETBG"
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""
	echo ""$WHITEBG"========================================================================================================================================$RESETBG"
	echo "                                                      "$BLINK$BLACKBG$GREEN"COVID-19 IN YOUR COUNTRY$RESETBG                                                              "
	echo ""$WHITEBG"----------------------------------------------------------------------------------------------------------------------------------------$RESETBG"
	sleep 3.0
	curl snf-878293.vm.okeanos.grnet.gr
	echo ""$WHITEBG"________________________________________________________________________________________________________________________________________$RESETBG"
	echo ""$WHITEBG"========================================================================================================================================$RESETBG"
        exit 0
}

##Usage and Help
usage()
{
  cat <<EOF
covidinfo

Description: Get the full detailed information of COVID19 in your terminal.

Usage: 
  -u  Update Termux-snippet Tools
  -h  Show the help
  -v  Get the tool version

Examples:
  covidinfo
EOF
}

##Options(flags)
while getopts "uvh" opt; do
  case "$opt" in
    \?) echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    h)  usage
        exit 0
        ;;
    v)  echo "Version $currentVersion"
        exit 0
        ;;
    u)
        getConfiguredClient || exit 1
        checkInternet || exit 1
        update
        exit 0
        ;;
  esac
done

##Driver
if [[ $# == 0 ]]; then
	getConfiguredpv || exit 0
        main || exit 0
  elif [[ $1 == "update" ]]; then
    getConfiguredClient || exit 1
    checkInternet || exit 1
    update || exit 1
    exit 0
  elif [[ $1 == "help" ]]; then
    usage
    exit 0
  else
        clear; echo "You shouldnt be here but maaaaaaybeee you slipped passed me, learn to use the tool!"; sleep 5; clear;
  usage
  exit 1
fi
